### ISSUE TITLE
Better usable JSON format

### ISSUE THREAD

**Issue by SofiyanIfren** [fawazahmed0/currency-api#23]
Hi,
I use your very nice API for a Discord.js bot, it is very simple to use, even if it would be prettier if the JSON format of the conversion URL (https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies/eur/jpy.json for example) response looked like :
`{
    "date": "2021-06-22",
    "change": { "currency " : "jpy", "amount" : "131.418702"}
}`
I think it would be more useful; if you want this from me, I can contribute by sending you a PR
Thank you for your work !

**Comment by fawazahmed0** [comment]
Recently someone [requested me](https://github.com/fawazahmed0/currency-api/issues/21) to add date/timestamp in json.
After adding that, my api broke for one person, due to date option, see [this](https://github.com/fawazahmed0/currency-api/issues/22).

So I will not add anything new or remove anything from the JSON( or change the format of JSON), otherwise it will break for old users, I hope you understand that.

Thank you for considering this 👍

**Comment by SofiyanIfren** [comment]
Ok I understand, thank you for your work !

Le mer. 23 juin 2021 à 12:36, Fawaz Ahmed ***@***.***> a
écrit :
