### ISSUE TITLE
Service is Totally Failing

### ISSUE THREAD

**Issue by amandugar** [fawazahmed0/currency-api#89]
@fawazahmed0 Can you check https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies/usd/gbp.min.json why latest is also failing

**Comment by fawazahmed0** [comment]
cleanup process did not go well, but anyways, the `latest` urls should work now

**Comment by YehorLesnev** [comment]
dates from 2023-08-20 to 2023-11-08 will not be available at all or just for some time?

**Comment by fawazahmed0** [comment]
The dates will not be available, because Github actions has timeout limit of 6 hours
If it is possible to make Github actions run for 7 hours, all the dates can be brought back.


**What happened?**
During [cleaning process](https://github.com/fawazahmed0/currency-api/actions/runs/6807087954/job/18509353837) or more specifically during force push the github actions got timeout due to 6 hours. So the 100 or so commits did not get push.
It just actions to run for 30mins more to push those remaining 100 commits.
